---
- name: Install SNMP and prerequisites
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - snmp
    - snmp-mibs-downloader
    
- name: Configure SNMP
  template:
    src: snmpd.j2
    dest: /etc/snmp/snmpd.conf
    owner: root
    group: root
    mode: 644
  notify:
    - Restart SNMP