---
- name: 'Remove existing container'
  docker_container:
    state: 'absent'
    name: 'ddclient'

- name: 'Create user'
  user:
    state: 'present'
    name: 'ddclient'
    system: yes
    comment: 'ddclient container system user'
    create_home: no
    home: '{{ configs_dir }}/ddclient'
    shell: '/usr/sbin/nologin'
  register: 'ddclient_user'

- name: 'Create home directory'
  file:
    state: 'directory'
    path: '{{ ddclient_user.home }}'
    owner: '{{ ddclient_user.uid }}'
    group: '{{ ddclient_user.group }}'
    mode: '0700'

- name: 'Setup config file'
  when: 'subdomains is defined'
  template:
    src: 'ddclient.conf.j2'
    dest: '{{ configs_dir }}/ddclient/ddclient.conf'
    owner: '{{ ddclient_user.uid }}'
    group: '{{ ddclient_user.group }}'
    mode: '0600'

- name: 'Deploy container'
  docker_container:
    state: 'started'
    name: 'ddclient'
    image: 'linuxserver/ddclient:latest'
    pull: yes
    volumes:
      - '{{ configs_dir }}/ddclient:/config'
    networks:
      - name: 'cloudnet'
        aliases:
          - 'ddclient'
    networks_cli_compatible: yes
    labels:
      traefik.enable: 'false'
    env:
      PUID: '{{ ddclient_user.uid }}'
      PGID: '{{ ddclient_user.group }}'
      TZ: '{{ timezone }}'
    purge_networks: yes
    memory: '50M'
    pids_limit: '20'
    restart_policy: 'on-failure'
    restart_retries: '5'
