---
- name: 'Add HWRaid repositry key'
  become: yes
  apt_key:
    state: 'present'
    url: 'https://hwraid.le-vert.net/debian/hwraid.le-vert.net.gpg.key'

- name: 'Add HWRaid apt repository'
  become: yes
  apt_repository:
    state: 'present'
    repo: 'deb https://hwraid.le-vert.net/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} main'

- name: 'Update apt cache and install package'
  become: yes
  apt:
    state: 'present'
    name:
      - 'sas2ircu'
    update_cache: yes
