---
- name: Add Snapraid repository
  apt_repository:
    repo: ppa:tikhonov/snapraid
    state: present

- name: Install Snapraid
  apt:
    name: snapraid
    state: present
    update_cache: yes

- name: Configure Snapraid
  template:
    src: snapraid.j2
    dest: /etc/snapraid.conf
    owner: root
    group: root
    mode: 0640

- name: Create mount folders
  file:
    path: "{{ mount_dir }}/{{ item.name }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ disks }}"

- name: Modify fstab config
  blockinfile:
    path: /etc/fstab
    backup: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertafter: EOF
    block: |
      # SnapRAID Data Disks
      UUID={{ item.8.uuid }} {{ mount_dir }}/{{ item.8.name }}     ext4    defaults        0       2
      UUID={{ item.9.uuid }} {{ mount_dir }}/{{ item.9.name }}    ext4    defaults        0       2
      UUID={{ item.10.uuid }} {{ mount_dir }}/{{ item.10.name }}     ext4    defaults        0       2
      UUID={{ item.12.uuid }} {{ mount_dir }}/{{ item.12.name }}     ext4    defaults        0       2
      UUID={{ item.13.uuid }} {{ mount_dir }}/{{ item.13.name }}     ext4    defaults        0       2
      UUID={{ item.14.uuid }} {{ mount_dir }}/{{ item.14.name }}     ext4    defaults        0       2

      # SnapRAID Parity Disks
      UUID={{ item.11.uuid }} {{ mount_dir }}/{{ item.11.name }}     ext4    defaults        0       2
      UUID={{ item.15.uuid }} {{ mount_dir }}/{{ item.15.name }}     ext4    defaults        0       2

      # MergerFS Disk Pool
      {{ mount_dir }}/{{ item.8.name }}:{{ mount_dir }}/{{ item.9.name }}:{{ mount_dir }}/{{ item.10.name }}:{{ mount_dir }}/{{ item.12.name }}:{{ mount_dir }}/{{ item.13.name }}:{{ mount_dir }}/{{ item.14.name }} /storage fuse.mergerfs category.create=eplfs,moveonenospc=true,defaults,allow_other,minfreespace=20G,fsname=StoragePool
  with_items:
    - "{{ disks }}"
