---
- name: 'Include Cloudflare DNS tasks'
  include_role:
    name: 'cloudflare-dns'
  vars:
    subdomain: 'radarr'

- name: 'Create user'
  user:
    state: 'present'
    name: 'radarr'
    group: '{{ media_group }}'
    system: yes
    comment: 'Radarr container system user'
    create_home: no
    home: '{{ configs_dir }}/radarr'
    shell: '/usr/sbin/nologin'
  register: 'radarr_user'

- name: 'Create home directory'
  file:
    state: 'directory'
    path: '{{ radarr_user.home }}'
    owner: '{{ radarr_user.uid }}'
    group: '{{ radarr_user.group }}'
    mode: '0755'

- name: 'Create and start linuxserver container'
  docker_container:
    state: 'started'
    name: 'radarr'
    image: 'linuxserver/radarr:latest'
    pull: yes
    volumes:
      - '{{ configs_dir }}/radarr:/config'
      - '{{ download_dir }}:/downloads'
      - '{{ movies_dir }}:/movies'
      - '/etc/localtime:/etc/localtime:ro'
    networks:
      - name: 'cloudnet'
        aliases:
          - 'radarr'
    networks_cli_compatible: yes
    labels:
      traefik.enable: 'true'
      traefik.http.routers.radarr.rule: 'Host(`radarr.{{ domain }}`)'
      traefik.http.routers.radarr.tls: 'true'
      traefik.http.routers.radarr.tls.certresolver: 'letsencrypt'
      traefik.http.routers.radarr.tls.domains[0].main: '{{ domain }}'
      traefik.http.routers.radarr.tls.domains[0].sans: '*.{{ domain }}'
      traefik.http.services.radarr.loadbalancer.server.port: '7878'
    env:
      PUID: '{{ radarr_user.uid }}'
      PGID: '{{ radarr_user.group }}'
      TZ: '{{ timezone }}'
      UMASK: '002'
    purge_networks: yes
    pids_limit: '50'
    restart_policy: 'on-failure'
    restart_retries: '5'
    healthcheck:
      start_period: '2s'
      test: 'curl --fail --head --silent http://localhost:7878/movies/ || exit 1'
      interval: '10s'
