---
- name: 'Remove non-official binaries'
  apt:
    state: 'absent'
    name:
      - 'speedtest-cli'

- name: 'Install dependencies'
  apt:
    state: 'present'
    name:
      - 'gnupg1'
      - 'apt-transport-https'
      - 'dirmngr'

- name: 'Add apt key by ID from ubuntu keyserver'
  apt_key:
    keyserver: 'keyserver.ubuntu.com'
    id: '379CE192D401AB61'

- name: 'Add repository into sources list'
  apt_repository:
    state: 'present'
    repo: 'deb https://ookla.bintray.com/debian generic main'
    filename: 'speedtest'

- name: 'Update apt cache and install speedtest binary'
  apt:
    state: 'present'
    name:
      - 'speedtest'
    update_cache: yes
