---
- name: 'Install dependencies'
  apt:
    state: 'present'
    name:
      - 'sg3-utils'
      - 'smp-utils'
      - 'python3-pip'

- name: 'Install sasutils via Pip'
  pip:
    state: 'present'
    name: 'sasutils'
    executable: 'pip3'
