---
- name: 'Include Cloudflare DNS tasks'
  include_role:
    name: 'cloudflare-dns'
  vars:
    subdomain: '{{ item }}'
  loop:
    - 'www'
    - 'organizr'

- name: 'Create user'
  user:
    state: 'present'
    name: 'organizr'
    system: yes
    comment: 'Organizr container system user'
    create_home: no
    home: '{{ configs_dir }}/organizr'
    shell: '/usr/sbin/nologin'
  register: 'organizr_user'

- name: 'Create home directory'
  file:
    state: 'directory'
    path: '{{ organizr_user.home }}'
    owner: '{{ organizr_user.uid }}'
    group: '{{ organizr_user.group }}'
    mode: '0755'

- name: 'Create and start organizr container'
  docker_container:
    state: 'started'
    name: 'organizr'
    image: 'organizr/organizr:latest'
    pull: yes
    volumes:
      - '{{ configs_dir }}/organizr:/config'
    networks:
      - name: 'cloudnet'
        aliases:
          - 'organizr'
    networks_cli_compatible: yes
    labels:
      traefik.enable: 'true'
      traefik.http.routers.organizr.service: 'organizr'
      traefik.http.routers.organizr.rule: 'Host(`www.{{ domain }}`)'
      traefik.http.routers.organizr.tls: 'true'
      traefik.http.routers.organizr.tls.certresolver: 'letsencrypt'
      traefik.http.routers.organizr.tls.domains[0].main: '{{ domain }}'
      traefik.http.routers.organizr.tls.domains[0].sans: '*.{{ domain }}'
      traefik.http.services.organizr.loadbalancer.server.port: '80'
    env:
      PUID: '{{ organizr_user.uid }}'
      PGID: '{{ organizr_user.group }}'
      TZ: '{{ timezone }}'
    purge_networks: yes
    restart_policy: 'always'
