---
- name: Download and install Mergerfs
  become: yes
  apt:
    deb: "https://github.com/trapexit/mergerfs/releases/download/{{ mergerfs_version }}/mergerfs_{{ mergerfs_version }}.{{ ansible_distribution }}-{{ ansible_distribution_release }}_amd64.deb"

- name: Create mount directory
  become: yes
  file:
    state: 'directory'
    path: "{{ data_dir }}"
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Add mergerfs mount to fstab and mount it
  become: yes
  mount:
    state: 'mounted'
    path: "{{ data_dir }}"
    src: "{{ mounts | join(':') }}"
    fstype: 'fuse.mergerfs'
    opts: "{{ mergerfs_mount_opts | join(',') | default ('defaults') }}"
    dump: '0'
    passno: '0'
    backup: yes
