---
- name: Create user
  become: yes
  user:
    name: "{{ item.name }}"
    state: present
    groups: "{{ item.groups }}"
    append: yes
    create_home: yes
    home: "{{ item.home }}"
    shell: "{{ item.shell }}"
    comment: "{{ item.comment }}"
  loop: "{{ users }}"
  loop_control:
    label: "{{ item.name }}"

- name: Add authorised keys
  authorized_key:
    user: "{{ item.0.name }}"
    state: present
    key: "{{ item.1 }}"
  loop: "{{ users | subelements('keys') | default(omit) }}"
  loop_control:
    label: "{{ item.1 }}"
