---
- name: 'Create user'
  become: yes
  user:
    state: 'present'
    name: '{{ item.name }}'
    groups: '{{ item.groups }}'
    append: yes
    create_home: yes
    home: '{{ item.home }}'
    shell: '{{ item.shell }}'
    comment: '{{ item.comment }}'
  loop: '{{ users }}'
  loop_control:
    label: '{{ item.name }}'

- name: 'Add authorised keys'
  authorized_key:
    state: 'present'
    user: '{{ item.0.name }}'
    key: '{{ item.1 }}'
  loop: '{{ users | subelements("keys") | default(omit) }}'
  loop_control:
    label: '{{ item.1 }}'
