---
- name: 'Include install tasks'
  when: 'nzbget.enabled | default(false) |bool'
  include_tasks:
    file: 'install.yml'

- name: 'Include uninstall tasks'
  when: 'not nzbget.enabled | default(false) |bool'
  include_tasks:
    file: 'uninstall.yml'
