---
- name: 'Stop and remove container'
  docker_container:
    state: 'absent'
    name: 'nzbget'
    image: 'linuxserver/nzbget:latest'

- name: 'Remove container image'
  docker_image:
    state: 'absent'
    name: 'linuxserver/nzbget:latest'

- name: 'Remove user'
  user:
    state: 'absent'
    name: 'nzbget'
  register: 'nzbget_user'

- name: 'Include Cloudflare DNS tasks'
  include_role:
    name: 'cloudflare-dns'
    tasks_from: 'removal'
  vars:
    subdomain: 'nzbget'
