---
- name: Sabnzbd container
  docker_container:
    state: started
    name: sabnzbd
    image: "{{ sabnzbd_image }}"
    pull: true
    volumes:
      - "{{ configs_dir }}/sabnzbd:/config"
      - "{{ download_dir }}:/downloads"
      - "{{ download_dir}}/incomplete:/incomplete-downloads"
    ports:
      - "127.0.0.1:8010:8080"
    env:
      PUID={{ users.0.uid }}
      PGID=1001
      TZ={{ timezone }}
    restart_policy: always
  notify:
    - Remove old images
  tags: sabnzbd

- name: Transmission container
  docker_container:
    state: started
    name: transmission
    image: "{{ transmission_image }}"
    pull: true
    volumes:
      - "{{ configs_dir }}/transmission:/config"
      - "{{ download_dir}}:/downloads"
      - "{{ media_dir }}/watch:/watch"
    ports:
      - "127.0.0.1:9091:9091"
      - "127.0.0.1:51413:51413"
    env:
      PUID={{ users.5.uid }}
      PGID=1001
      TZ={{ timezone }}
    restart_policy: always
  notify:
    - Remove old images
  tags: transmission

- name: Hydra container
  docker_container:
    state: started
    name: hydra
    image: "{{ hydra_image }}"
    pull: true
    volumes:
      - "{{ configs_dir }}/hydra:/config"
      - "{{ download_dir }}:/downloads"
    ports:
      - "127.0.0.1:5075:5075"
    env:
      PUID={{ users.11.uid }}
      PGID=65534
      TZ={{ timezone }}
    links:
      - "sabnzbd:sabnzbd"
    restart_policy: always
  notify:
    - Remove old images
  tags: hydra

- name: Plex container
  docker_container:
    state: started
    name: plex
    image: "{{ plex_image }}"
    pull: true
    volumes:
      - "{{ configs_dir }}/plex:/config"
      - "{{ media_dir }}/Videos:/data:ro"
      - "/home/transcode:/transcode"
    ports:
      - "32469:32469"
      - "32400:32400"
      - "32401:32401"
      - "3005:3005"
      - "8324:8324"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    env:
      PLEX_CLAIM="claim-MWWps1QYNDksfn2o7sBc"
      ADVERTISE_IP="http://{{ ansible_default_ipv4.address }}:32400/"
      PLEX_UID=111
      PLEX_GID=118
      CHANGE_CONFIG_DIR_OWNERSHIP=true
      TZ={{ timezone }}
    network_mode: host
    restart_policy: always
  notify:
    - Remove old images
  tags: plex

- name: Sonarr container
  docker_container:
    state: started
    name: sonarr
    image: "{{ sonarr_image }}"
    pull: true
    volumes:
      - "{{ configs_dir }}/sonarr:/config"
      - "{{ download_dir }}:/downloads"
      - "{{ media_dir }}/Videos/TV:/tv"
      - "/dev/rtc:/rtc:ro"
    ports:
      - "127.0.0.1:8989:8989"
    env:
      PUID={{ users.3.uid }}
      PGID=1001
      TZ={{ timezone }}
    links:
      - "sabnzbd:sabnzbd"
      - "transmission:transmission"
      - "hydra:hydra"
    restart_policy: always
  notify:
    - Remove old images
  tags: sonarr

- name: Tautulli container
  docker_container:
    state: started
    name: tautulli
    image: "{{ tautulli_image }}"
    pull: true
    volumes:
      - "{{ configs_dir }}/plexpy:/config"
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ configs_dir}}/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro"
    ports:
      - "127.0.0.1:8283:8181"
    env:
      PUID={{ users.8.uid }}
      PGID=65534
      TZ={{ timezone }}
    restart_policy: always
  notify:
    - Remove old images
  tags: plexpy

- name: Unifi container
  docker_container:
    state: absent
    name: unifi
    image: "{{ unifi_image }}"
    pull: true
    volumes:
      - "{{ configs_dir }}/unifi:/config"
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
      - "8843:8843"
      - "8880:8880"
    env:
      PUID={{ users.12.uid }}
      PGID=65534
      TZ={{ timezone }}
    restart_policy: always
  notify:
    - Remove old images
  tags: unifi

- name: Radarr
  docker_container:
    state: started
    name: radarr
    image: "{{ radarr_image }}"
    pull: true
    volumes:
      - "{{ configs_dir }}/radarr:/config"
      - "{{ download_dir }}:/downloads"
      - "{{ media_dir }}/Videos/Movies:/movies"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "127.0.0.1:7878:7878"
    env:
      PUID={{ users.1.uid }}
      PGID=1001
      TZ={{ timezone }}
    links:
      - "sabnzbd:sabnzbd"
      - "transmission:transmission"
    restart_policy: always
  notify:
    - Remove old images
  tags: radarr

- name: Lidarr
  docker_container:
    state: started
    name: lidarr
    image: "{{ lidarr_image }}"
    pull: true
    volumes:
      - "{{ configs_dir }}/lidarr:/config"
      - "{{ download_dir }}:/downloads"
      - "{{ media_dir }}/Videos/Music:/music"
    ports:
      - "127.0.0.1:8686:8686"
    env:
      PUID={{ users.4.uid }}
      PGID=1001
      TZ={{ timezone }}
    links:
      - "sabnzbd:sabnzbd"
      - "transmission:transmission"
    restart_policy: always
  notify:
    - Remove old images
  tags: lidarr

- name: Beets
  docker_container:
    state: started
    name: beets
    image: "{{ beets_image }}"
    pull: true
    volumes:
      - "{{ configs_dir }}/beets:/config"
      - "{{ download_dir }}:/downloads"
      - "{{ media_dir }}/Videos/Music:/music"
    ports:
      - "127.0.0.1:8337:8337"
    env:
      PUID={{ users.12.uid }}
      PGID=1001
      TZ={{ timezone }}
    restart_policy: always
    notify:
      - Remove old images
    tags: beets
