---
- name: Sabnzbd container
  docker_container:
    name: sabnzbd
    image: linuxserver/sabnzbd
    volumes:
      - "{{ configs_dir }}/sabnzbd:/config"
      - "{{ download_dir }}:/downloads"
      - "{{ download_dir}}/incomplete:/incomplete-downloads"
    ports:
      - "127.0.0.1:8010:8080"
    env:
      PUID={{ users.0.uid }}
      PGID=1001
      TZ={{ timezone }}
    restart_policy: always
  tags: sabnzbd

- name: Transmission container
  docker_container:
    name: transmission
    image: linuxserver/transmission
    volumes:
      - "{{ configs_dir }}/transmission:/config"
      - "{{ download_dir}}:/downloads"
      - "{{ media_dir }}/watch:/watch"
    ports:
      - "127.0.0.1:9091:9091"
      - "127.0.0.1:51413:51413"
    env:
      PUID={{ users.5.uid }}
      PGID=1001
      TZ={{ timezone }}
    restart_policy: always
  tags: transmission

- name: Hydra container
  docker_container:
    name: hydra
    image: linuxserver/hydra
    volumes:
      - "{{ configs_dir }}/hydra:/config"
      - "{{ download_dir }}:/downloads"
    ports:
      - "127.0.0.1:5075:5075"
    env:
      PUID={{ users.11.uid }}
      PGID=65534
      TZ={{ timezone }}
    links:
      - "sabnzbd:sabnzbd"
    restart_policy: always
  tags: hydra

- name: Plex container
  docker_container:
    name: plex
    image: plexinc/pms-docker:plexpass
    volumes:
      - "{{ configs_dir }}/plex:/config"
      - "{{ media_dir }}/Videos:/data:ro"
      - "/home/transcode:/transcode"
    ports:
      - "32469:32469"
      - "32400:32400"
      - "32401:32401"
      - "3005:3005"
      - "8324:8324"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    env:
      PLEX_CLAIM="CLAIM-DESXP8ERRL2SNGWRDWUK"
      ADVERTISE_IP="http://192.168.1.50:32400/"
      PUID={{ users.14.uid }}
      PGID=1001
      TZ={{ timezone }}
    restart_policy: always
  tags: plex

- name: Sonarr container
  docker_container:
    name: sonarr
    image: linuxserver/sonarr
    volumes:
      - "{{ configs_dir }}/sonarr:/config"
      - "{{ download_dir }}:/downloads"
      - "{{ media_dir }}/Videos/TV:/tv"
      - "/dev/rtc:/rtc:ro"
    ports:
      - "127.0.0.1:8989:8989"
    env:
      PUID={{ users.3.uid }}
      PGID=1001
      TZ={{ timezone }}
    links:
      - "sabnzbd:sabnzbd"
      - "transmission:transmission"
      - "hydra:hydra"
    restart_policy: always
  tags: sonarr

- name: Couchpotato container
  docker_container:
    name: couchpotato
    image: linuxserver/couchpotato
    volumes:
      - "{{ configs_dir }}/couchpotato:/config"
      - "{{ download_dir }}:/downloads"
      - "{{ media_dir }}/Videos/Movies:/movies"
    ports:
      - "127.0.0.1:8925:5050"
    env:
      PUID={{ users.1.uid }}
      PGID=1001
      TZ={{ timezone }}
    links:
      - "sabnzbd:sabnzbd"
      - "transmission:transmission"
      - "hydra:hydra"
    restart_policy: always
  tags: couchpotato

- name: Musicbrainz container
  docker_container:
    name: musicbrainz
    image: linuxserver/musicbrainz:68
    volumes:
      - "{{ configs_dir }}/musicbrainz:/config"
      - "/var/local/musicbrainz/data:/data"
    ports:
      - "127.0.0.1:5000:5000"
    env:
      PUID={{ users.7.uid }}
      PGID=1001
      TZ={{ timezone }}
      BRAINZCODE={{ metabrainz_code }}
      WEBADDRESS={{ ansible_default_ipv4.address }}
    restart_policy: always
  tags: musicbrainz

- name: Headphones container
  docker_container:
    name: headphones
    image: bytesized/headphones
    volumes:
      - "{{ configs_dir }}/headphones:/config"
      - "{{ download_dir }}:/media"
      - "{{ media_dir }}/Music:/data"
    ports:
      - "127.0.0.1:8181:8181"
    env:
      PUID={{ users.4.uid }}
      PGID=1001
      TZ={{ timezone }}
    links:
      - "sabnzbd:sabnzbd"
      - "transmission:transmission"
      - "hydra:hydra"
      - "musicbrainz:musicbrainz"
    restart_policy: always
  tags: headphones

- name: Plexpy container
  docker_container:
    name: plexpy
    image: linuxserver/plexpy
    volumes:
      - "{{ configs_dir }}/plexpy:/config"
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ configs_dir}}/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro"
    ports:
      - "127.0.0.1:8283:8181"
    env:
      PUID={{ users.8.uid }}
      PGID=65534
      TZ={{ timezone }}
    links:
      - "plex:plex"
    restart_policy: always
  tags: plexpy

- name: Unifi container
  docker_container:
    name: unifi
    image: linuxserver/unifi
    volumes:
      - "{{ configs_dir }}/unifi:/config"
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
      - "8843:8843"
      - "8880:8880"
    env:
      PUID={{ users.12.uid }}
      PGID=65534
      TZ={{ timezone }}
    restart_policy: always
  tags: unifi

- name: Mylar container
  docker_container:
    name: mylar
    image: linuxserver/mylar
    volumes:
      - "{{ configs_dir }}/mylar:/config"
      - "{{ download_dir }}:/downloads"
      - "{{ media_dir }}/Comics:/comics"
    ports:
      - "127.0.0.1:8090:8090"
    env:
      PUID={{ users.2.uid }}
      PGID=1001
      TZ={{ timezone }}
    links:
      - "sabnzbd:sabnzbd"
      - "transmission:transmission"
      - "hydra:hydra"
    restart_policy: always
  tags: mylar

- name: Lazylibrarian container
  docker_container:
    name: lazylibrarian
    image: linuxserver/lazylibrarian
    volumes:
      - "{{ configs_dir }}/lazylibrarian:/config"
      - "{{ download_dir }}:/downloads"
      - "{{ media_dir }}/Ebooks:/books"
    ports:
      - "127.0.0.1:5299:5299"
    env:
      PUID={{ users.9.uid }}
      PGID=1001
      TZ={{ timezone }}
    links:
      - "sabnzbd:sabnzbd"
      - "transmission:transmission"
      - "hydra:hydra"
    restart_policy: always
  tags: lazylibrarian
