---
- name: Install ctop binary
  get_url:
    url: "https://github.com/bcicen/ctop/releases/download/v{{ ctop_version | default('0.7.5') }}/ctop-{{ ctop_version | default('0.7.5') }}-linux-amd64"
    dest: /usr/local/bin/ctop
    mode: '0755'

- name: Check binary is installed correctly
  shell: ctop -v
  register: shell_output
  failed_when: "ctop_version is not in shell_output.stdout"
  changed_when: false
