---
- name: Add repository and update apt cache
  apt_repository:
    repo: ppa:tikhonov/snapraid
    state: present
    update_cache: true

- name: Install Snapraid
  apt:
    name: snapraid
    state: latest

- name: Configure Snapraid
  template:
    src: snapraid.conf.j2
    dest: /etc/snapraid.conf
    owner: root
    group: root
    mode: '0640'

- name: Include fstab tasks
  when: snapraid_disks is defined
  include_role:
    name: fstab
  vars:
    label: "{{ item.name }}"
    mount: "{{ item.mount }}"
  loop: "{{ snapraid_disks }}"

- name: Include mergerfs tasks
  when: snapraid_disks is defined
  include_role:
    name: mergerfs
  vars:
    mounts: "{{ snapraid_disks | selectattr('type', '==', 'data') | map(attribute='mount') | list }}"
