---
- name: Get device name from WWN
  shell: "lsblk -dn -o WWN,NAME | grep '{{ item.wwn }}' | awk '{ print $2 }'"
  register: device_name
  changed_when: false

- name: Set fact about current disk
  set_fact:
    disk: "{{ '/dev/' + device_name.stdout }}"

- name: Check partition
  become: yes
  parted:
    state: info
    device: "{{ disk }}"
  register: disk_info

- debug:
    var: disk_info

#- name: Create partition
#  parted:
#    state: present
#    device: /dev/sdd
#    number: 1
#    label: gpt
#    name: primary
#    part_start: '0%'
#    part_end: '100%'
#  register: new_disk

# - name: Format new partitions
#   filesystem:
#     dev: "{{ item.device}}1"
#     fstype: "{{ item.fstype }}"
#   with_items:
#     - "{{ disks }}"

# - name: Get UUID for partition
#   command: blkid -s UUID -o value {{ item.device }}1
#   register: disk_uuid
#   with_items:
#     - "{{ disks }}"
#   changed_when: false
