---
- name: Install prerequisites
  apt:
    name:
      - "parted"
      - "xfsprogs"
      - "btrfs-tools"
    state: present

- name: Check partition
  parted:
    state: info
    device: /dev/sdd
  register: disk

- name: Create partition
  parted:
    state: present
    device: /dev/sdd
    number: 1
    label: gpt
    name: primary
    part_start: '0%'
    part_end: '100%'
  register: new_disk

- debug:
    var: disk

- debug:
    var: new_disk

# - name: Format new partitions
#   filesystem:
#     dev: "{{ item.device}}1"
#     fstype: "{{ item.fstype }}"
#   with_items:
#     - "{{ disks }}"

# - name: Get UUID for partition
#   command: blkid -s UUID -o value {{ item.device }}1
#   register: disk_uuid
#   with_items:
#     - "{{ disks }}"
#   changed_when: false

# - name: Mount new partitions
#   mount:
#     state: mounted
#     path: "{{ item.0.mount }}"
#     src: "UUID={{ item.1.stdout }}"
#     fstype: "{{ item.0.fstype }}"
#     opts: "{{ item.0.mount_options }}"
#   with_together:
#     - "{{ disks }}"
#     - "{{ disk_uuid.results }}"
