---
- name: Clone Gramarr
  git:
    repo: 'https://github.com/alcmoraes/gramarr.git'
    dest: /opt/gramarr
    update: true

- name: Create config.json
  template:
    src: config.json.j2
    dest: /opt/gramarr/config.json
    mode: '0640'
    force: true

- name: Build Gramarr image
  docker_image:
    build:
      path: /opt/gramarr
    name: linuxserver/gramarr
    tag: latest
    source: build

- name: Gramarr
  docker_container:
    state: started
    name: gramarr
    image: linuxserver/gramarr:latest
    networks:
      - name: cloudnet
        aliases:
          - gramarr
    networks_cli_compatible: true
    restart_policy: always
  tags: gramarr
