---
- name: 'Remove older versions on Ubuntu'
  when: '(ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04")'
  become: yes
  apt:
    state: 'absent'
    name:
      - 'docker'
      - 'docker-engine'
      - 'docker.io'
      - 'containerd'
      - 'runc'

- name: 'Install prerequisites for Ubuntu'
  when: '(ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04")'
  become: yes
  apt:
    state: 'present'
    name:
      - 'linux-image-extra-{{ ansible_kernel }}'
      - 'linux-image-extra-virtual'

- name: 'Install dependencies'
  become: yes
  apt:
    state: 'present'
    name:
      - 'apt-transport-https'
      - 'ca-certificates'
      - 'curl'
      - 'gnupg-agent'
      - 'software-properties-common'
      - 'python-pip'

- name: 'Add GPG key'
  become: yes
  apt_key:
    state: 'present'
    url: 'https://download.docker.com/linux/ubuntu/gpg'

- name: 'Add repository to sources'
  become: yes
  apt_repository:
    state: 'present'
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'

- name: 'Updated the cache and install docker-ce'
  apt:
    state: 'present'
    name: 'docker-ce'
    update_cache: yes
  register: 'install_docker'

- name: 'Install Docker SDK for Python'
  pip:
    state: 'present'
    name: 'docker'

- name: 'Include docker-compose tasks'
  include_role:
    name: 'docker-compose'
