---
- name: Remove older versions on Ubuntu
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04")
  become: yes
  apt:
    name:
      - "docker"
      - "docker-engine"
      - "docker.io"
      - "containerd"
      - "runc"
    state: absent

- name: Install prerequisites for Ubuntu
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04")
  become: yes
  apt:
    name:
      - "linux-image-extra-{{ ansible_kernel }}"
      - "linux-image-extra-virtual"
    state: present

- name: Install dependencies
  become: yes
  apt:
    name:
      - "apt-transport-https"
      - "ca-certificates"
      - "curl"
      - "gnupg-agent"
      - "software-properties-common"
      - "python-pip"
    state: present

- name: Add GPG key
  become: yes
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Add repository to sources
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Updated the cache and install docker-ce
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  register: install_docker

- name: Install Docker SDK for Python
  pip:
    name: docker
    state: present

- name: Include docker-compose tasks
  include_role:
    name: docker-compose
