---
- name: 'whoami'
  docker_container:
    state: 'started'
    name: 'whoami'
    image: 'containous/whoami:latest'
    pull: yes
    networks:
      - name: 'cloudnet'
        aliases:
          - 'whoami'
    networks_cli_compatible: yes
    labels:
      traefik.enable: 'true'
      traefik.http.routers.whoami.service: 'whoami'
      traefik.http.routers.whoami.rule: 'Host(`whoami.deathbox.co.uk`)'
      traefik.http.routers.whoami.tls: 'true'
      traefik.http.routers.whoami.tls.certresolver: 'letsencrypt'
      traefik.http.services.whoami.loadbalancer.server.port: '80'
    purge_networks: yes
    restart_policy: 'always'
