---
- name: setup ansible authentication
  hosts: testservers
  remote_user: simon

  tasks:
    - name: remove public key
      authorized_key:
        user: simon
        state: absent
        key: "{{ lookup('file', '/home/simon/.ssh/id_rsa.pub') }}"
    - name: install aptitude
      apt:
        name: aptitude
        state: present
      become: yes
