---
- name: setup ansible authentication
  hosts: testservers
  remote_user: simon
  become: yes
  become_method: sudo

  tasks:
    - name: create ansible user
      user:
        name: ansible
        state: present
        uid: 666
        group: sudo
        shell: /bin/bash
        append: yes
    - name: edit visudo
      lineinfile:
        path: /etc/sudoers
        state: present
        insertafter: EOF
        line: 'ansible   ALL=NOPASSWD: ALL'
    - name: add public key
      authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '/home/simon/.ssh/id_rsa.pub') }}"
    - name: disable password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PasswordAuthentication yes/m'
        line: 'PasswordAuthentication no'
      notify: restart openssh

  handlers:
    - name: restart openssh
      service: name=sshd state=restarted
