---
- name: 'Install openssh-server package'
  become: yes
  package:
    state: 'present'
    name:
      - 'openssh-server'

- name: 'Disable password authentication'
  become: yes
  lineinfile:
    state: 'present'
    path: '/etc/ssh/sshd_config'
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    backup: yes
    validate: '/usr/sbin/sshd -t -f %s'
  notify:
    - 'Restart SSHD service'

- name: 'Allow SSH through firewall'
  ufw:
    rule: 'allow'
    port: '22'
    proto: 'tcp'
    comment: 'OpenSSH Server'
